services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
      platforms:
        - linux/amd64
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FRED_API_KEY=${FRED_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    volumes:
      - ./app:/app/app
      - ./backend:/app/backend
      - ./logs:/app/logs
    networks:
      - finbot-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      platforms:
        - linux/amd64
    ports:
      - "8502:8502"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
    networks:
      - finbot-network

networks:
  finbot-network:
    driver: bridge 